### DISCUSSION TITLE
Can't get ALIAS_DOMAINS to work

### DISCUSSION THREAD

**Discussion by bflemi3** [BetaHuhn/deploy-to-vercel-action#156] [Q&A]
First off, thanks for taking your personal time to build this action. I'm new to GitHub Actions and it's saved me time in getting my workflows up & running. Much appreciated 🍺 

I'm having an issue getting my development workflow to assign the deployment to `dev.mydomain.me`. The workflow step gets stuck at `Assigning custom domains to Vercel deployment`. On the Vercel side, the deployment succeeds but only to the random preview url that Vercel automatically generates. The assignment to `dev.mydomain.me` never occurs.

GitHub Action
![Screen Shot 2022-04-25 at 8 51 56 AM](https://user-images.githubusercontent.com/794675/165092903-e2243969-a5eb-4631-aa8e-c8cad86e12c2.png)

Vercel Deployment
![Screen Shot 2022-04-25 at 8 50 44 AM](https://user-images.githubusercontent.com/794675/165092666-3f0c2bf3-a98f-4364-8505-52b186b6b8bd.png)

I've noticed on Vercel that my domain `dev.mydomain.me` has the production tag on it but not sure why, not sure if that makes a difference and/or how to change that. I've also disconnected the GitHub integration to my repo via the Vercel UI and the `vercel.json` file in the project. Just wanted to eliminate as many points of failure as possible.
![Screen Shot 2022-04-25 at 8 55 03 AM](https://user-images.githubusercontent.com/794675/165093865-4200801d-dc90-4df6-8f39-5449aaf47d0b.png)

My GitHub workflow yml
```yml
name: Deploy Development CI
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: false
          ALIAS_DOMAINS: | 
            dev.mydomain.me 
          # I also tried `ALIAS_DOMAINS: dev.mydomain.me` on one line

```

vercel.json
```json
{
  "github": {
    "enabled": false
  }
}
```

I'm positive there's something I'm missing, just not sure what. Thanks for your help.
