### DISCUSSION TITLE
ALIAS_DOMAINS not working

### DISCUSSION THREAD

**Discussion by anthify** [BetaHuhn/deploy-to-vercel-action#173] [Q&A]
Hi 👋 ,

I recently added your script to deploy to previews, beta, and production using GH Actions.

In the Vercel dashboard I have the domain setup and it's pointing to the branch name `beta` which was working when I wasn't GH Actions, but since moving it has not been applying the custom domains.

I decided to try and add `ALIAS_DOMAINS` just like the docs, but the GH Action just hangs when it tries to apply custom domain and never works.

It never gets further than this:

```shell
Successfully deployed to Vercel!
Assigning custom domains to Vercel deployment
```

vercel.json
```json
{
  "version": 2,
  "public": false,
  "github": {
    "enabled": false
  }
}

```

Part of my GH Actions file
```yaml
deploy_beta:
    name: Deploy Beta ✨
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [release]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          ALIAS_DOMAINS: |
            my.custom-domain.com
          PRODUCTION: false 
```
