### DISCUSSION TITLE
How to get deploy url from action output to put on enviroment url

### DISCUSSION THREAD

**Discussion by rafae2k** [BetaHuhn/deploy-to-vercel-action#204] [Q&A]
I want to get the deployed URL from the vercel action to pass to the environment URL on my workflow.

To show like this on my pipeline
<img width="615" alt="Screen Shot 2022-07-14 at 13 58 15" src="https://user-images.githubusercontent.com/53544360/179038339-f1d4ed70-8d39-432a-8467-e8226766418d.png">

It is possible? I saw something like getting from ${{ steps.version.outputs.TAG_NAME }} where TAG_NAME would be the output from vercel action, but couldn't find any output to use

**Comment by mountainash** [comment]
You need to put an "id" on the step that uses this projects action, and then reference that id to get the outputted value into your following step.

**Reply by mountainash** [reply]
eg 
```yaml
      - name: Deploy website - Vercel ▲
        id: verceldeploy
        uses: mountainash/deploy-to-vercel-action@v2.4.0
        ... (later)
        
        
      DEPLOYMENT_CREATED: ${{ steps.verceldeploy.outputs.DEPLOYMENT_CREATED }}
      DEPLOYMENT_UNIQUE_URL: ${{ steps.verceldeploy.outputs.DEPLOYMENT_UNIQUE_URL }}
```
