### DISCUSSION TITLE
Is it possible to generate multiple deployment comments in same pull request?

### DISCUSSION THREAD

**Discussion by MartinLupa** [BetaHuhn/deploy-to-vercel-action#375] [Q&A]
I am working with a monorepo and a workflow that deploys two different nextjs apps. Is it possible to generate one deployment comment for each app? In the current state, the later app being deployed overwrites the first one, so in the end I only have one comment in my PR and can't find the way to generate multiple of them. Is this feature supported by the action? Thanks!

Reusable action (only pertinent fragment):
```
runs:
  using: composite
  steps:
    - name: Deploy to Vercel
      id: vercel-deploy
      uses: BetaHuhn/deploy-to-vercel-action@v1
      with:
        GITHUB_TOKEN: ${{ inputs.github-token }} 
        VERCEL_TOKEN: ${{ inputs.vercel-token }} 
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }} 
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }} 
        PRODUCTION: ${{ inputs.production-deployment }}
        BUILD_ENV: |
          CONTENTFUL_SHARED_CONTENT_ENV=${{ inputs.contentful-env }}
        CREATE_COMMENT: false
    - uses: phulsechinmay/rewritable-pr-comment@v0.3.0
      if: ${{ steps.vercel-deploy.outputs.DEPLOYMENT_CREATED }}
      with:
        message: |
          <h3>${{ inputs.app-name }}</h3>
          This pull request has been deployed to Vercel.
          <table>
            <tr>
              <td><strong>✅ Preview:</strong></td>
              <td><a href='${{ steps.vercel-deploy.outputs.PREVIEW_URL }}'>${{ steps.vercel-deploy.outputs.PREVIEW_URL }}</a></td>
            </tr>
            <tr>
              <td><strong>🔍 Inspect:</strong></td>
              <td><a href='${{ steps.vercel-deploy.outputs.DEPLOYMENT_INSPECTOR_URL }}'>${{ steps.vercel-deploy.outputs.DEPLOYMENT_INSPECTOR_URL }}</a></td>
            </tr>
          </table>
        GITHUB_TOKEN: ${{ inputs.github-token }}
        COMMENT_IDENTIFIER: '${{ inputs.app-name }}'
```
Workflow (calls reusable action twice):

```
build-app-1:
    name: Build app 1 🔨
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v3
        name: Checkout repo
      - uses: "./.github/actions/setup-pnpm"
        name: Setup PNPM
      - name: Vercel Preview Deployment
        id: vercel-deploy
        uses: ./.github/actions/deploy
        with:
          app-name: 'App 1'
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ vars.VERCEL_ORG_ID }} 
          vercel-project-id: ${{ vars.VERCEL_APP_1_PROJECT_ID }} 
          production-deployment: false

build-app-2:
    name: Build app 2 🔨
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
        name: Checkout repo
      - uses: "./.github/actions/setup-pnpm"
        name: Setup PNPM
      - name: Vercel Preview Deployment
        id: vercel-deploy
        uses: ./.github/actions/deploy
        with:
          app-name: 'App 2'
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ vars.VERCEL_ORG_ID }} 
          vercel-project-id: ${{ vars.VERCEL_APP_2_PROJECT_ID }}
          production-deployment: false
```
PR Outcome:
![image](https://github.com/BetaHuhn/deploy-to-vercel-action/assets/80256770/18b2d85f-2f6a-4199-8a3c-12e569e61f06)

Expected outcome: to generate two comments like the one above, one for App 1 and a different one for App 2.
