### DISCUSSION TITLE
Change branch ref

### DISCUSSION THREAD

**Discussion by maxbec** [BetaHuhn/deploy-to-vercel-action#377] [Q&A]
I have a github action which triggers on a merged pull_request:

```
on:
  pull_request:
    branches:
      - dev
    types:
      - closed
```

How can i tell the vercel deploy action to use the base branch for deployment and not the head branch.
Because in that moment wenn the pr is merged the head branch is deleted.

```
      - id: script
        uses: actions/github-script@v3
        with:
          script: |
            core.setOutput('ref', 'dev')

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'dev'
```

This is not working unfortunately.
