### DISCUSSION TITLE
Branch-specific URL not getting created

### DISCUSSION THREAD

**Discussion by alexflint** [BetaHuhn/deploy-to-vercel-action#394] [Q&A]
When I use this action to deploy code to github, vercel creates only the commit-specific preview URL, not the branch-specific preview URL. The commit-specific preview URL changes on each commit, so when I share it with coworkers and then push more commits to a branch, I have to send a new URL.

The github action I'm using looks like this:

```yaml
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      # Deploy on vercel
      - name: Deploy
        id: deploy
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.VERCEL_BOT_GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ vars.VERCEL_TEAM }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT }}
          PRODUCTION: ${{ github.ref_name == 'main' }}
```

Do I need to do anything more to get a branch-specific URL? When I use the vercel github app, I do get the branch-specific (as well as commit-specific) URL.
