### DISCUSSION TITLE
Skip output 'PREVIEW_URL' since it may contain secret.

### DISCUSSION THREAD

**Discussion by gianpaj** [BetaHuhn/deploy-to-vercel-action#400] [Q&A]
I get this error running this GH action job. Any ideas?

```
Skip output 'PREVIEW_URL' since it may contain secret.
```

```yaml

jobs:
    deploy-to-vercel:
        runs-on: ubuntu-latest
        outputs:
            PREVIEW_URL: ${{ steps.deploy-to-vercel-step.outputs.PREVIEW_URL }}
        permissions:
            contents: read
            pull-requests: write
            deployments: write
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4.0.0

            - name: Install Vercel CLI
              run: pnpm add --global vercel@canary

            - name: Deploy to Vercel Action
              id: deploy-to-vercel-step
              uses: BetaHuhn/deploy-to-vercel-action@v1.10.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  PRODUCTION: ${{ inputs.PRODUCTION }}
```
