### ISSUE TITLE
Error: Cannot read property 'login' of null

### ISSUE THREAD

**Issue by wottpal** [BetaHuhn/deploy-to-vercel-action#187]
While deploying I get the following error, do you have any ideas?

```
Error: Cannot read property 'login' of null
```
<img width="578" alt="Screen Shot 2022-06-21 at 01 26 07" src="https://user-images.githubusercontent.com/3930150/174688523-d842edb0-22b3-4bb7-9cb5-7b55e6fdd48a.png">

The deploy script is basically copy'n'paste from the docs:
```
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy to Vercel CI

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: false
```
