### ISSUE TITLE
`FORCE` option unrecognized

### ISSUE THREAD

**Issue by wottpal** [BetaHuhn/deploy-to-vercel-action#192]
In the docs you have the `FORCE` option to skip vercels build cache. But when used throws the following warning:

<img width="1058" alt="Screen Shot 2022-07-02 at 15 45 26" src="https://user-images.githubusercontent.com/3930150/177004069-b685c861-9478-4fb2-a137-f715a3b70142.png">

**Comment by Wizyma** [comment]
Hey @wottpal it's actually me who made a PR for the force options, you need to specify the excat version of the action and the force options is available from the version `1.9.0` ! 

I have something like 
```
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 'Deploy'
        uses: BetaHuhn/deploy-to-vercel-action@v1.9.0
```


Hope it helps
