### ISSUE TITLE
Document GitHub fine-grained personal token permissions

### ISSUE THREAD

**Issue by Siilwyn** [BetaHuhn/deploy-to-vercel-action#353]
Thoughts on adding needed permissions to the readme?

After some trial and error it seems that the 'new' personal access tokens need the following permissions:
![image](https://user-images.githubusercontent.com/5701149/235460343-1921e630-eff7-438a-b341-6f6d3f9f42fa.png)

**Comment by davidar** [comment]
You can also use GITHUB_TOKEN with these permissions:

```yaml
permissions: 
   contents: read 
   pull-requests: write 
   deployments: write
```
