### ISSUE TITLE
PREVIEW defaults to false on pull requests

### ISSUE THREAD

**Issue by alexflint** [BetaHuhn/deploy-to-vercel-action#387]
**🐞 Describe the bug**

In the docs you say that the default value for PRODUCTION is "true (false for PR deployments)", but when I use this action from a pull request, it creates a production deployment on vercel.

**📚 To Reproduce**

Create a pull request on a repository with an ordinary github action like this:

```
name: Vercel Preview Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout
        uses: actions/checkout@v4

      # Deploy on vercel
      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
```

**💡 Expected behavior**

Creates a preview deployment

**🖼️ Screenshots**

N/A

**⚙️ Environment**

I am using `BetaHuhn/deploy-to-vercel-action@v1`

**📋 Additional context**

N/A
