### ISSUE TITLE
PR_PREVIEW_DOMAIN does not use the vercel team

### ISSUE THREAD

**Issue by armandabric** [BetaHuhn/deploy-to-vercel-action#88]
**🐞 Describe the bug**

I'm unable to use a PR preview domain (the `PR_PREVIEW_DOMAIN` option) when the project is link to a team.

Without the `PR_PREVIEW_DOMAIN` the project is correctly deployed:

```yaml
      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_xxxxxxxxxxxxxx
          VERCEL_PROJECT_ID: xxxxxxxxxxxx
          GITHUB_DEPLOYMENT: false
          PR_LABELS: false
          DELETE_EXISTING_COMMENT: false
```

When I add the `PR_PREVIEW_DOMAIN`:

```yaml
          PR_PREVIEW_DOMAIN: '{REPO}-{PR}.vercel.app'
```

I got this error:

```
Error: undefinedVercel CLI 23.1.2
Error! Failed to find deployment "ibe-ak7jds436-gogaille.vercel.app" under armandabric
```

`armandabric` is my personal vercel account. And the `ibe` project is a project of one of my Vercel team.

**🖼️ Screenshots**

![image](https://user-images.githubusercontent.com/95120/134652970-91a0810f-83c2-48da-b4f8-6b5b724147c7.png)

**⚙️ Environment**
- Action version: [e.g. v1.0.0]
